// Fushigi no Dungeon 2: Fuurai no Shiren
// #ID = 2899

// Item Dictionary
Items= {
    
    
}

Sprites = {
    "Shiren": 0x00,
    "Mamul": 0x01,
    "MinionOfDeath": 0x02,
    "Gyazar": 0x03,
    "Bowya": 0x04,
    "Gamara": 0x05,
    "Debuta": 0x06,
    "MistHermit": 0x07,
    "FlamePriest": 0x08,
    "Midoro": 0x09,
    "Theftodo": 0x0a,
    "Parthenos": 0x0b,
    "KingiTribe": 0x0c,
    "WrigglingHoney": 0x0d,
    "EtherDevil": 0x0e,
    "Nduba": 0x0f,
    "IronHead": 0x10,
    "MonsterDaikon": 0x11,
    "AbsorberLarva": 0x12,
    "WoodArmor": 0x13,
    "Dragon": 0x14,
    "Tauros": 0x15,
    "HealerRabbit": 0x16,
    "KimenMusha": 0x17,
    "GhostMusha": 0x18,
    "MasterChicken": 0x19,
    "Chicken": 0x1a,
    "DarkOwl": 0x1b,
    "KnifeGator": 0x1c,
    "Peetan": 0x1d,
    "FaceFirstWarrior": 0x1e,
    "Shoebell": 0x1f,
    "ImpasseDragon": 0x20,
    "Pumkorepkin": 0x21,
    "OldManTank": 0x22,
    "MonsterNigiriBeast": 0x23,
    "Norojo": 0x24,
    "SkeletonMage": 0x25,
    "Gaze": 0x26,
    "SpinningPolygon": 0x27,
    "MashokuBug": 0x28,
    "SoldierAnt": 0x29,
    "Karakuroid": 0x2a,
    "Dremlas": 0x2b,
    "Haboon": 0x2c,
    "FieldRaider": 0x2d,
    "KidTank": 0x2e,
    "BeanBandit": 0x38,
    "KidTengu": 0x39
}

Items = {
    "Club": 0x00,
    "Nagamaki": 0x01,
    "BufoosCleaver": 0x02,
    "Katana": 0x03,
    "DragonKiller": 0x04,
    "Dotanuki": 0x05,
    "GokenManjikabra": 0x06,
    "ExorcistSickle": 0x07,
    "Pickaxe": 0x08,
    "AccuracySword": 0x09,
    "MinotaurAxe": 0x0a,
    "YotoKamaitachi": 0x0b,
    "OneEyeKiller": 0x0c,
    "DrainBuster": 0x0d,
    "Kajinfumato": 0x0e,
    "HikenKaburasutegi": 0x0f,
    "WoodArrow": 0x10,
    "IronArrow": 0x11,
    "SilverArrow": 0x12,
    "LeatherShield": 0x16,
    "BronzeShield": 0x17,
    "AntidoteShield": 0x18,
    "WoodenShield": 0x19,
    "IronShield": 0x1a,
    "DragonShield": 0x1b,
    "FumaShield": 0x1c,
    "BattleCounter": 0x1d,
    "HeavyShield": 0x1e,
    "EchoShield": 0x1f,
    "ReflexShield": 0x20,
    "GildedShield": 0x21,
    "DisposableShield": 0x22,
    "MineNabariShield": 0x23,
    "TodoShield": 0x24,
    "RasenFumaShield": 0x25,
    "MedicalHerb": 0x28,
    "OtogiriSo": 0x29,
    "HappyHerb": 0x2a,
    "VisionHerb": 0x2b,
    "DragonHerb": 0x2c,
    "InvincibleHerb": 0x2d,
    "AngelSeed": 0x2e,
    "RevivalHerb": 0x2f,
    "VanishingHerb": 0x30,
    "WrigglingHerb": 0x31,
    "UnluckySeed": 0x32,
    "SuperUnluckySeed": 0x33,
    "KingiTribeSeed": 0x34,
    "ForgetfulHerb": 0x35,
    "LifeHerb": 0x37,
    "ExpansionSeed": 0x38,
    "ContractionSeed": 0x39,
    "SpeechSeed": 0x3a,
    "PowerHerb": 0x3b,
    "AntidoteHerb": 0x3c,
    "PoisonHerb": 0x3d,
    "ConfusionHerb": 0x3e,
    "SleepHerb": 0x3f,
    "Weed": 0x40,
    "PurifyScroll": 0x56,
    "IdentifyScroll": 0x57,
    "LightScroll": 0x58,
    "BigpotScroll": 0x59,
    "AirslashScroll": 0x5a,
    "LockjawScroll": 0x5b,
    "TrapScroll": 0x5d,
    "CrisisScroll": 0x5e,
    "FastfoeScroll": 0x5f,
    "SlumberScroll": 0x60,
    "PowerupScroll": 0x61,
    "DetonateScroll": 0x63,
    "BigroomScroll": 0x64,
    "MonsterHouseScroll": 0x65,
    "ConfuseScroll": 0x66,
    "GenocideScroll": 0x67,
    "BlankScroll": 0x68,
    "LostScroll": 0x69,
    "HeavenScroll": 0x6a,
    "EarthScroll": 0x6b,
    "ChromeScroll": 0x6c,
    "WithdrawScroll": 0x6d,
    "SlipperyScroll": 0x6e,
    "SealingStaff": 0x7c,
    "BlowbackStaff": 0x7d,
    "HappyStaff": 0x7e,
    "UnluckyStaff": 0x7f,
    "DecoyStaff": 0x80,
    "SwapStaff": 0x81,
    "BufoosStaff": 0x82,
    "SkeletonMageStaff": 0x83,
    "ParalysisStaff": 0x84,
    "BuyTimeStaff": 0x85,
    "PaindividingStaff": 0x86,
    "PassageBracer": 0x93,
    "BargainBracer": 0x94,
    "TrapperBracer": 0x95,
    "LevelholderBracer": 0x96,
    "HealingBracer": 0x97,
    "RustproofBracer": 0x98,
    "CriticalBracer": 0x99,
    "PainBracer": 0x9a,
    "BlessingBracer": 0x9b,
    "PenetrationBracer": 0x9c,
    "HappyBracer": 0x9d,
    "ClumsinessBracer": 0x9e,
    "FarSightBracer": 0x9f,
    "ClearMindBracer": 0xa0,
    "IdBracer": 0xa1,
    "RiceBall": 0xae,
    "BigRiceBall": 0xaf,
    "RottenRiceBall": 0xb0,
    "HugeRiceBall": 0xb1,
    "SpecialRiceBall": 0xb2,
    "HoldingPot": 0xb4,
    "HidingPot": 0xb5,
    "DividingPot": 0xb6,
    "StrengtheningPot": 0xb7,
    "IdPot": 0xb8,
    "BackPot": 0xb9,
    "StoragePot": 0xba,
    "WeakeningPot": 0xbb,
    "BottomlessPot": 0xbd,
    "MonsterPot": 0xbe,
    "TransformPot": 0xbf,
    "FusionPot": 0xc0,
    "TodoPot": 0xc1,
    "GaibaraPot": 0xc2,
    "StupidLookingPot": 0xc3,
    "UnbreakablePot": 0xc4,
    "StressRelievingPot": 0xc5,
    "Meat": 0xe0,
    "Money": 0xe5,
    "Nothing": 0xff
}

Dungeons = {
    "Main": 0x0a,
    "Trials": 0x01,
    "Scroll": 0x03,
    "Food": 0x02,
    "Fei": 0x04
}


function steps() => word(0x0000AC)
function input() => byte(0x000BCE)
function input_2() => byte(0x000BCF)
function relatedToNewChampion() => byte(0x0050C1)
function playerXcoordinate() => word(0x0080C4)
function playerYcoordinate() => word(0x0080C6)
function horizontalDirection() => word(0x0080D0)
function verticalDirection() => word(0x0080D2)
function locationIdBreaksInDungeons() => dword(0x0080D4)
function playerDirection() => byte(0x008161)
function shirenHp() => byte(0x008604)
function shirenMaxHp() => byte(0x008618)
function shirenLevel() => byte(0x008640)
function shirenExperience() => word(0x008654)
function shieldStrength() => byte(0x0086A4)
function currentSprite() => byte(0x0087BC)
function tempQuests() => byte(0x887c)
function shirenStrength() => byte(0x00893D)
function shirenMaxStrength() => byte(0x00893E)
function money() => dword(0x00893F)
function satiation() => word(0x008943)
function maximumSatiation() => word(0x008945)
function currentWeaponStrength() => byte(0x008974)
function visionHerbEffectActive() => byte(0x008975)
function farsightBracerEffect() => byte(0x008983)
function penetrationBracerEffect() => byte(0x00898A)
function clearMindBracerEffect() => byte(0x00898C)
function transformed() => byte(0x00899B)
function highestFloorReached() => byte(0x00D294)
function priest() => byte(0x00D295)
function kamahige() => byte(0x00D296)
function oryu() => byte(0x00D297)
function gaibara() => byte(0x00D298)
function zatoKechi() => byte(0x00D299)
function naoki() => byte(0x00D29D)
function numberOfAttempts() => byte(0x00D2A1)
function feisProblemsSolved() => byte(0x00D2AA)
function secretDungeonUnlockKeys() => byte(0x00D2AB)
function pekeji() => byte(0x00d29a)
function lostGirl() => byte(0x00D31D)
function smithyHoldingPickaxeOvernight() => byte(0x00D3EE)
function dungeonId() => byte(0x00D5EE)
function dungeonIdWord() => word(0x00D5EE)
function inDungeonFlag() => byte(0x00D5FD)
function highScore() => word(0x00D613)
function currentScore() => word(0x00D61C)
function demo() => byte(0x016001)
function shirenIsControllable() => byte(0x019CDA)
function array6ByteStructWarehouseData() => byte(0x025D1C)
function displayLevel() =>byte(0x00862c)
function disciple() => byte(0x00d29c)
function floor() => byte(0x00d5f2)


// Normal Stuff
function demoProtection() => demo() != 0x81
function inDungeon(dungeon) => byte(0xd5ee) == dungeon
function progression(floor) => inDungeon(Dungeons["Main"]) && floor() == floor && prev(inDungeonFlag()) == 1 && inDungeonFlag() == 0
function trials(floor) => inDungeon(Dungeons["Trials"]) && prev(floor()) == floor && floor() == floor + 1
function wonGame() => inDungeon(Dungeons["Main"]) && prev(bit0(0xD2AB)) < bit0(0xD2AB)
function wonGameWithoutStorage() => inDungeon(Dungeons["Main"]) && prev(bit0(0xd2b2)) < bit0(0xd2b2)
function wonFei() => prev(bit4(0xD2AB)) < bit4(0xD2AB)
function identifiedItem() { // To see if the player has ID'd any item
    StaffBase = 0x9088
    StaffBase2 = 0x9090
    BracerBase = 0x909f
    PotBase = 0x90c0
    return any_of(range(0, 6), i => prev(byte(StaffBase + i)) == 0 && byte(StaffBase + i) == 1) ||
           any_of(range(0,2), i => prev(byte(StaffBase2 + i)) == 0 && byte(StaffBase2 + i) == 1) ||
           any_of(range(0, 14), i => prev(byte(BracerBase + i)) == 0 && byte(BracerBase + i) == 1) ||
           any_of(range(0, 13), i => prev(byte(PotBase + i)) == 0 && byte(PotBase + i) == 1)
}
function feiProblems(num) => prev(feisProblemsSolved()) == num - 1 && feisProblemsSolved() == num

// Item Array Parsing
function weaponEquipped() => byte(0x008970)
function shieldEquipped() => byte(0x008971)
function bracerEquipped() => byte(0x008972)
function projectileEquipped() => byte(0x008973)

// Bases for each of the arrays. The inventory array is 20 Bytes, all the others are 127 Bytes. 
InventoryBase = 0x894f
ItemBase = 0x8B8C
StateBase = 0x8C8C
SubstateBase = 0x8D0C
CurseBase = 0x008c0c
DiscoveredBase = 0x008d8c
PotItemBase = 0x008e0c
ShopItemBase = 0x008e8c
ExtraQualities1Base = 0x008f0c
ExtraQualities2Base = 0x008f8c

MaxOffset = 0x7e

// Read the index from the inventory slot, add it to the larger item array base, then read the final ID
function addedToInventory(ID) {
    return any_of(range(0, 19), i => 
    prev(byte(InventoryBase + i)) == 0xff &&
    byte(InventoryBase + i) <= MaxOffset &&
    byte(ItemBase + byte(InventoryBase + i)) == ID
    )
}

// See if the amount of items in your inventory has decreased
function removedFromInventory() {
    return any_of(range(0,19), i =>
        prev(byte(InventoryBase + i)) <= MaxOffset &&
        byte(InventoryBase + i) == Items["Nothing"]
    )
}

// For seeing if a weapon has been enhanced. Skips the inventory check because items leave yourinventory when they get enhanced.
function strengthened(str = 0) {
    if (str == 0) {
        return any_of(range(0, 126), i => 
        byte(ItemBase + i) <= 0x0f &&
        prev(byte(ItemBase + i)) == byte(ItemBase + i) &&
        prev(byte(StateBase + i)) < byte(StateBase + i) &&
        byte(StateBase + i) <= 99
        )
    }
    else {
        return any_of(range(0, 126), i => 
        byte(ItemBase + i) <= 0x0f &&
        prev(byte(ItemBase + i)) == byte(ItemBase + i) &&
        prev(byte(StateBase + i)) < str &&
        byte(StateBase + i) >= str &&
        byte(StateBase + i) <= 99
        )
    }
}

function forged(ID1,ID2) { // For forging achievements
    return any_of(range(0, 126), i => 
    prev(byte(ItemBase + i)) == ID1 &&  
    byte(ItemBase + i) == ID2
    )
}

function addedToFloor(ID) { // For pickaxe achievement, sees if an item has been added to the floor.
    return any_of(range(0,126), i =>
    prev(byte(ItemBase + i)) == 0xff &&
    byte(ItemBase + i) == ID
    )
}

function inventoryState(deltaState,state) {
    return any_of(range(0, 19), i => 
           prev(byte(ItemBase + byte(StateBase + i)) == deltaState) &&
           byte(ItemBase + byte(StateBase + i)) == state
           ) 
}

// Theft function
// Sees if an item disappeared from the shop, that it wasn't bought,and that you didn't get caught.
function shopTheft() {
        return byte(0x008995) == 0 &&
        prev(byte(0x00d5fd)) == byte(0x00d5fd) &&
        prev(floor()) == floor() && // Protection against the shop disappearing
        any_of(range(0, 126), i =>
        prev(byte(ItemBase + i)) == byte(ItemBase + i) &&
        prev(byte(ShopItemBase + i)) == 1 &&
        byte(ShopItemBase + i) == 0
        )
}

// Extra Quality checker for Synthesis achievements
function extraQuality(bita, bitb = byte, bitc = byte, bitd = byte) {
    if (bitb == byte) { // Equals 8 because Bit7 indicates that the weapon is forged, so +1.
        return any_of(range(0,126), i =>
            byte(ItemBase + i) <= Items["RasenFumaShield"] &&
            prev(bitcount(ExtraQualities1Base + i)) + prev(bitcount(ExtraQualities2Base + i)) <= 7 &&
            bitcount(ExtraQualities1Base + i) + bitcount(ExtraQualities2Base + i) >= 8
        )
    }
    else if (bitc == byte) {
        return any_of(range(0,126), i =>
            byte(ItemBase + i) <= Items["RasenFumaShield"] &&
            prev(bita(ExtraQualities1Base + i)) + prev(bitb(ExtraQualities1Base + i)) == 1 &&
            bita(ExtraQualities1Base + i) + bitb(ExtraQualities1Base + i) == 2
        )
    }
    else {
        return any_of(range(0,126), i =>
            byte(ItemBase + i) <= Items["RasenFumaShield"] &&
            prev(bita(ExtraQualities1Base + i)) + prev(bitb(ExtraQualities1Base + i)) +
            prev(bitc(ExtraQualities1Base + i)) + prev(bitd(ExtraQualities1Base + i)) == 1 &&
            bita(ExtraQualities1Base + i) + bitb(ExtraQualities1Base + i) +
            bitc(ExtraQualities1Base + i) + bitd(ExtraQualities1Base + i) == 2
        )
    }
}

achievement("A Lazy Forest Stroll", "Clear Floor 4 and arrive at Bamboo Village", 5, 
    demoProtection() && byte(0x00d5fe) != 0x01 && progression(4),
    id=0, published="", modified="", badge="0", type="Progression", set=0)

achievement("A Walk on Cliff's Edge", "Clear Floor 7 and arrive at Summit Town", 5, 
    demoProtection() && byte(0x00d5fe) != 0x01 && progression(7),
    id=0, published="", modified="", badge="0", type="Progression", set=0)

achievement("Down the Valley...", "Clear Floor 14 and arrive at Cracked Boulder Valley", 10, 
    demoProtection() && byte(0x00d5fe) != 0x01 && progression(14),
    id=0, published="", modified="", badge="0", type="Progression", set=0)

achievement("...and Through the Caves", "Clear Floor 21 and arrive at Underground River Town", 10, 
    demoProtection() && byte(0x00d5fe) != 0x01 && progression(21),
    id=0, published="", modified="", badge="0", type="Progression", set=0)

achievement("The Master Swordsmith's Trial", "Clear Floor 27: Trial of the Genma", 5, 
    demoProtection() && byte(0x00d5fe) != 0x01 && trials(27),
    id=0, published="", modified="", badge="0", type="Progression", set=0)

achievement("The Fearsome Dragon's Trial", "Clear Floor 28: Trial of the Dragon's Wail", 5, 
    demoProtection() && byte(0x00d5fe) != 0x01 && trials(28),
    id=0, published="", modified="", badge="0", type="Progression", set=0)

achievement("Death's Trial", "Clear Floor 29: The Final Trial and reach the Golden City", 5, 
    demoProtection() && byte(0x00d5fe) != 0x01 && progression(29),
    id=0, published="", modified="", badge="0", type="Progression", set=0)
    
achievement("A Golden Wish", "Free the Golden Condor", 50, 
    demoProtection() && wonGame(),
    id=0, published="", modified="", badge="0", type="Win_Condition", set=0)
    

achievement("Everything Must Die", "Gain the ability to create Massacre scrolls by beating the game without ever using item storage", 50, 
    demoProtection() && floor() == 0x1e && wonGameWithoutStorage(),
    id=0, published="", modified="", badge="0", type="", set=0)
    
    
achievement("A New Champion", "Submit a first place score to the Main Dungeon leaderboard", 10, 
    demoProtection() && prev(dword(0x02600b)) < dword(0x02600b),
    id=0, published="", modified="", badge="0", type="", set=0)


achievement("Amateur Masseur", "Receive a massage from Masseur Zato-Kechi", 1, 
    demoProtection() && prev(zatoKechi()) == 0 && zatoKechi() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)

achievement("At Least He's on Your Side", "Have Zato-Kechi join you in your travels", 5, 
    demoProtection() && prev(zatoKechi()) == 3 && zatoKechi() == 4,
    id=0, published="", modified="", badge="0", type="", set=0)

achievement("Medusa's Twin", "Get blinded by a mysterious woman", 1, 
    demoProtection() && prev(oryu()) == 0 && oryu() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("An Eye for an Eye", "Have Oryu the Blinder join you in your travels", 5, 
    demoProtection() && prev(oryu()) == 3 && oryu() == 4,
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("A Brother from Another Mother?", "Tell Pekeji he can call you his brother... Or tell him he can't", 1, 
    demoProtection() && prev(pekeji()) == 0 && pekeji() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("A Brother That Counts on You", "Give Pekeji the money he needs to make a wonderful shop", 3, 
    demoProtection() && prev(pekeji()) == 1 && pekeji() == 4,
    id=0, published="", modified="", badge="0", type="", set=0)
     
achievement("A Brother You Can Count On... Sometimes...", "Have Pekeji join you in your travels", 5, 
    demoProtection() && prev(pekeji()) == 4 && pekeji() == 5,
    id=0, published="", modified="", badge="0", type="", set=0)       
        
achievement("Family Reunited", "Reunite Surara with her parents and allow the Warehouse to open again", 5, 
    demoProtection() && prev(lostGirl()) == 1 && lostGirl() == 2,
    id=0, published="", modified="", badge="0", type="", set=0)      
 
achievement("Do-Gooder", "Heal a little girl's blindness and receive a reward", 5, 
    demoProtection() && prev(kamahige()) == kamahige() && prev(tempQuests()) == 1 && tempQuests() == 2,
    id=0, published="", modified="", badge="0", type="", set=0)        
    
achievement("Transforming Into Something Useful", "Eat a Monster Meat from a Level 3 monster", 10, 
    demoProtection() && transformed() == 0xff && displayLevel() == 3 && removedFromInventory(),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Invisible Walruses Everywhere!", "Steal an item from a shop with a Todo Pot", 5, 
    demoProtection() && shopTheft(),
    id=0, published="", modified="", badge="0", type="", set=0)
    
// There is a treasure achievement here that I'd rather just write in the UI, so it's not in the script.
    
achievement("The Power of Fusion", "Make a sword that is strong against two types of monsters", 5, 
    demoProtection() && extraQuality(bit0,bit1,bit2,bit3),
    id=0, published="", modified="", badge="0", type="", set=0)

achievement("Plus 1, Minus 1", "Make a shield that both slows hunger and speeds hunger", 5, 
    demoProtection() && extraQuality(bit0,bit1),
    id=0, published="", modified="", badge="0", type="", set=0)

achievement("The Ultimate Weapon", "Make a weapon or shield with seven extra effects", 10, 
    demoProtection() && extraQuality(0),
    id=0, published="", modified="", badge="0", type="", set=0)

achievement("Stronger than Ever", "Increase the strength of your weapon for the first time", 2, 
    demoProtection() && strengthened(),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("The Strongest of the Land", "Create a weapon with at least +50 Strength", 10, 
    demoProtection() && strengthened(50),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("One-of-a-Kind Katana", "Forge a Katana into a Kajinfumato", 25, 
    demoProtection() && forged(Items["Katana"],Items["Kajinfumato"]),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Hard-to-Pronounce Blade", "Forge a Goken-Manjikabra into a Hiken Kaburasutegi", 25, 
    demoProtection() && forged(Items["GokenManjikabra"],Items["HikenKaburasutegi"]),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Defense Is the Best Offense", "Forge a Fuma Shield into a Rasen-Fuma Shield", 25, 
    demoProtection() && forged(Items["FumaShield"],Items["RasenFumaShield"]),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Diggy Diggy Hole", "Forge an unbreakable Pickaxe", 10, 
    demoProtection() && inDungeonFlag() == 0 && (floor() == 0x04 || floor() == 0x07) && 
    addedToFloor(Items["Pickaxe"]),
    id=0, published="", modified="", badge="0", type="", set=0)

achievement("Jar Master", "Throw an Identify Scroll at Gaibara's Third Disciple and enable him to identify your pots", 5, 
    demoProtection() && prev(disciple() == 0) && disciple() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)    
    
achievement("Armband Expert", "Throw a Vision Herb at Kamahige and enable him to identify your armbands", 5, 
    demoProtection() && prev(kamahige() == 0) && kamahige() == 2,
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Educated Priest", "Throw a Purify Scroll at the Decrepit Old Man and enable him to remove curses from your items", 5, 
    demoProtection() && prev(priest() == 0) && priest() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)  
    
achievement("Nice Meat...", "Give some Mamul Meat to Chef Naoki", 1, 
    demoProtection() && prev(naoki() == 0) && naoki() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)  

achievement("Chef Escort", "Accompany Naoki to the Mountain Summit and agree to pay his fee", 5, 
    demoProtection() && prev(naoki() == 2) && naoki() == 5,
    id=0, published="", modified="", badge="0", type="", set=0)     

achievement("Expensive Service", "Give 10,000 Gitan to Naoki in total and receive a Bufoo's Staff", 10, 
    demoProtection() && prev(naoki() == 6) && naoki() == 7,
    id=0, published="", modified="", badge="0", type="", set=0)     
    
achievement("Chop Chop", "Clear Floor 10 of the Kitchen God dungeon", 10, 
    demoProtection() && inDungeon(Dungeons["Food"]) && prev(floor()) == 10 && floor() == 11,
    id=0, published="", modified="", badge="0", type="", set=0)         

achievement("Eating Like a Pro", "Clear Floor 20 of the Kitchen God dungeon", 25, 
    demoProtection() && inDungeon(Dungeons["Food"]) && prev(floor()) == 20 && floor() == 21,
    id=0, published="", modified="", badge="0", type="", set=0)  
    
achievement("The Rarest Meat", "Find Naoki inside the Kitchen God dungeon and receive a reward", 50, 
    demoProtection() && prev(naoki() == 9) && naoki() == 10,
    id=0, published="", modified="", badge="0", type="", set=0)  
    
achievement("Hope You Didn't Need That...", "Give one of your pots to Gaibara", 1, 
    demoProtection() && prev(gaibara() == 0) && gaibara() == 1,
    id=0, published="", modified="", badge="0", type="", set=0)     

achievement("The Ultimate Pot", "Receive the Synthesis Pot from Gaibara", 10, 
    demoProtection() && prev(gaibara() == 4) && gaibara() == 5,
    id=0, published="", modified="", badge="0", type="", set=0)     
    
achievement("Trapping Master", "Clear Floor 10 of the Scroll Cave dungeon", 10, 
    demoProtection() && inDungeon(Dungeons["Scroll"]) && prev(floor()) == 10 && floor() == 11,
    id=0, published="", modified="", badge="0", type="", set=0)        
    
achievement("This Might Be a Bomb", "Find Gaibara inside the Scroll Cave dungeon and receive a reward", 50, 
    demoProtection() && prev(gaibara() == 7) && gaibara() == 8,
    id=0, published="", modified="", badge="0", type="", set=0) 
    
achievement("The Beginning of a Long Journey", "Clear Fei's Problems 1-5", 5, 
    demoProtection() && feiProblems(5),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Basic Mechanics", "Clear Fei's Problems 6-10", 5, 
    demoProtection() && feiProblems(10),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Feeling Smart", "Clear Fei's Problems 11-15", 5, 
    demoProtection() && feiProblems(15),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Scores of Scrolls", "Clear Fei's Problems 16-20", 5, 
    demoProtection() && feiProblems(20),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Don't Forget to Throw!", "Clear Fei's Problems 21-25", 10, 
    demoProtection() && feiProblems(25),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Monster Properties", "Clear Fei's Problems 26-30", 10, 
    demoProtection() && feiProblems(30),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Distraction and Evasion", "Clear Fei's Problems 31-35", 10, 
    demoProtection() && feiProblems(35),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Watching Your Step", "Clear Fei's Problems 36-40", 10, 
    demoProtection() && feiProblems(40),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Wish the Rewards Were Better...", "Clear Fei's Problems 41-45", 10, 
    demoProtection() && feiProblems(45),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("The Hardest Puzzles", "Clear Fei's Problems 46-50", 25, 
    demoProtection() && wonFei(),
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("What Is Anything??", "Clear Floor 25 of Fei's Final Problem", 25, 
    demoProtection() && inDungeon(Dungeons["Fei"]) && prev(floor()) == 25 && floor() == 26,
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("Be Sure to Take Notes", "Clear Floor 50 of Fei's Final Problem", 50, 
    demoProtection() && inDungeon(Dungeons["Fei"]) && prev(floor()) == 50 && floor() == 51,
    id=0, published="", modified="", badge="0", type="", set=0)
    
achievement("The Other Side of the World", "Reach floor 100 of Fei's Final Problem and receive a mark on your savefile!", 100, 
    demoProtection() && prev(bit3(0x00d2ab)) < bit3(0x00d2ab),
    id=0, published="", modified="", badge="0", type="", set=0)
    
    
// Leaderboard Values
MainScore = 0x02600b
MainFloor = MainScore + 7
KitchenGodScore = 0x0267dc
KitchenGodFloor = KitchenGodScore + 7
ScrollCaveScore = 0x026fad
ScrollCaveFloor = ScrollCaveScore + 7
FinalProblemScore = 0x02777e
FinalProblemFloor = FinalProblemScore + 7

function firstPlaceFloor(num) {
    return prev(byte(num)) < byte(num)    
}
function firstPlaceScore(num) {
    return prev(dword(num)) < dword(num)    
}

leaderboard("Main Dungeon High Floor", "Get to the highest floor in the Main dungeon and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceFloor(MainFloor), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(byte(MainFloor)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )
    
leaderboard("Main Dungeon High Score", "Attain the highest score in the Main dungeon and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceScore(MainScore), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(dword(MainScore)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )

leaderboard("Kitchen God High Floor", "Get to the highest floor in the Kitchen God dungeon and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceFloor(KitchenGodFloor), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(byte(KitchenGodFloor)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )

leaderboard("Kitchen God High Score", "Attain the highest score in the Kitchen God dungeon and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceScore(KitchenGodScore), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(dword(KitchenGodScore)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )
    
leaderboard("Scroll Cave High Floor", "Get to the highest floor in the Scroll Cave dungeon and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceFloor(ScrollCaveFloor), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(byte(ScrollCaveFloor)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )

leaderboard("Scroll Cave High Score", "Attain the highest score in the Scroll Cave dungeon and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceScore(ScrollCaveScore), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(dword(ScrollCaveScore)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )

leaderboard("Fei's Final Problem High Floor", "Get to the highest floor in Fei's Final Problem and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceFloor(FinalProblemFloor), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(byte(FinalProblemFloor)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )

leaderboard("Fei's Final Problem High Score", "Attain the highest score in Fei's Final Problem and get first place in the Explorer's Ranking",
    demoProtection() && firstPlaceScore(FinalProblemScore), // Start
    always_false(), // Cancel - Never
    always_true(), // Submit - Always
    measured(dword(FinalProblemScore)), // Measured
    format="VALUE",lower_is_better=false, id=0
    )
    
